/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_leorblx_webtools_NativeBridge */

#ifndef _Included_me_leorblx_webtools_NativeBridge
#define _Included_me_leorblx_webtools_NativeBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_leorblx_webtools_NativeBridge
 * Method:    nativePhysicsCalc
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_me_leorblx_webtools_NativeBridge_nativePhysicsCalc
  (JNIEnv *, jobject, jstring);

/*
 * Class:     me_leorblx_webtools_NativeBridge
 * Method:    nativeBaseCarLookup
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_me_leorblx_webtools_NativeBridge_nativeBaseCarLookup
  (JNIEnv *, jobject, jstring);

/*
 * Class:     me_leorblx_webtools_NativeBridge
 * Method:    nativeDecrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_me_leorblx_webtools_NativeBridge_nativeDecrypt
  (JNIEnv *, jobject, jstring);

/*
 * Class:     me_leorblx_webtools_NativeBridge
 * Method:    getBaseCarNames
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_me_leorblx_webtools_NativeBridge_nativeGetBaseCarNames
  (JNIEnv *, jobject);
/*
 * Class:     me_leorblx_webtools_NativeBridge
 * Method:    getAllCarNames
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_me_leorblx_webtools_NativeBridge_nativeGetAllCarNames
    (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
